var searchData=
[
  ['salp_8945',['SALP',['../class_s_a_l_p.html',1,'']]],
  ['scalar_8946',['Scalar',['../class_stats___ram_1_1_scalar.html',1,'Stats_Ram']]],
  ['scalarbase_8947',['ScalarBase',['../class_stats_1_1_scalar_base.html',1,'Stats::ScalarBase&lt; Storage, T &gt;'],['../class_stats___ram_1_1_scalar_base.html',1,'Stats_Ram::ScalarBase&lt; ScalarType &gt;']]],
  ['scalarbase_3c_20average_20_3e_8948',['ScalarBase&lt; Average &gt;',['../class_stats___ram_1_1_scalar_base.html',1,'Stats_Ram']]],
  ['scalarbase_3c_20averagescalarstorage_2c_20double_20_3e_8949',['ScalarBase&lt; AverageScalarStorage, double &gt;',['../class_stats_1_1_scalar_base.html',1,'Stats']]],
  ['scalarbase_3c_20constvalue_20_3e_8950',['ScalarBase&lt; ConstValue &gt;',['../class_stats___ram_1_1_scalar_base.html',1,'Stats_Ram']]],
  ['scalarbase_3c_20countscalarstorage_2c_20uint64_5ft_20_3e_8951',['ScalarBase&lt; CountScalarStorage, uint64_t &gt;',['../class_stats_1_1_scalar_base.html',1,'Stats']]],
  ['scalarbase_3c_20maxscalarstorage_2c_20uint64_5ft_20_3e_8952',['ScalarBase&lt; MaxScalarStorage, uint64_t &gt;',['../class_stats_1_1_scalar_base.html',1,'Stats']]],
  ['scalarbase_3c_20scalar_20_3e_8953',['ScalarBase&lt; Scalar &gt;',['../class_stats___ram_1_1_scalar_base.html',1,'Stats_Ram']]],
  ['scalarstat_8954',['ScalarStat',['../class_scalar_stat.html',1,'']]],
  ['scalarstatbase_8955',['ScalarStatBase',['../class_scalar_stat_base.html',1,'']]],
  ['scalarstatbase_3c_20stats_5fram_3a_3aaverage_20_3e_8956',['ScalarStatBase&lt; Stats_Ram::Average &gt;',['../class_scalar_stat_base.html',1,'']]],
  ['scalarstatbase_3c_20stats_5fram_3a_3ascalar_20_3e_8957',['ScalarStatBase&lt; Stats_Ram::Scalar &gt;',['../class_scalar_stat_base.html',1,'']]],
  ['scalarstorage_8958',['ScalarStorage',['../class_stats_1_1_scalar_storage.html',1,'Stats']]],
  ['scalarstorage_3c_20double_20_3e_8959',['ScalarStorage&lt; double &gt;',['../class_stats_1_1_scalar_storage.html',1,'Stats']]],
  ['scalarstorage_3c_20uint64_5ft_20_3e_8960',['ScalarStorage&lt; uint64_t &gt;',['../class_stats_1_1_scalar_storage.html',1,'Stats']]],
  ['scalingfactor_8961',['ScalingFactor',['../class_technology_parameter_1_1_scaling_factor.html',1,'TechnologyParameter']]],
  ['scheduler_8962',['Scheduler',['../class_scheduler.html',1,'']]],
  ['scheduler_5funit_8963',['scheduler_unit',['../classscheduler__unit.html',1,'']]],
  ['scheduleru_8964',['SchedulerU',['../class_scheduler_u.html',1,'']]],
  ['scoreboard_8965',['Scoreboard',['../class_scoreboard.html',1,'']]],
  ['selalloc_8966',['SelAlloc',['../class_sel_alloc.html',1,'']]],
  ['selection_5flogic_8967',['selection_logic',['../classselection__logic.html',1,'']]],
  ['separableallocator_8968',['SeparableAllocator',['../class_separable_allocator.html',1,'']]],
  ['separableinputfirstallocator_8969',['SeparableInputFirstAllocator',['../class_separable_input_first_allocator.html',1,'']]],
  ['separableoutputfirstallocator_8970',['SeparableOutputFirstAllocator',['../class_separable_output_first_allocator.html',1,'']]],
  ['sfu_8971',['sfu',['../classsfu.html',1,'']]],
  ['shader_5fcore_5fconfig_8972',['shader_core_config',['../structshader__core__config.html',1,'']]],
  ['shader_5fcore_5fctx_8973',['shader_core_ctx',['../classshader__core__ctx.html',1,'']]],
  ['shader_5fcore_5fmem_5ffetch_5fallocator_8974',['shader_core_mem_fetch_allocator',['../classshader__core__mem__fetch__allocator.html',1,'']]],
  ['shader_5fcore_5fpower_5fstats_5fpod_8975',['shader_core_power_stats_pod',['../structshader__core__power__stats__pod.html',1,'']]],
  ['shader_5fcore_5fstats_8976',['shader_core_stats',['../classshader__core__stats.html',1,'']]],
  ['shader_5fcore_5fstats_5fpod_8977',['shader_core_stats_pod',['../structshader__core__stats__pod.html',1,'']]],
  ['shader_5fmemory_5finterface_8978',['shader_memory_interface',['../classshader__memory__interface.html',1,'']]],
  ['shader_5fpreempt_5foverhead_8979',['shader_preempt_overhead',['../classshader__preempt__overhead.html',1,'']]],
  ['shader_5fpreempt_5foverhead_5fcompare_8980',['shader_preempt_overhead_compare',['../classshader__preempt__overhead__compare.html',1,'']]],
  ['sharedbufferpolicy_8981',['SharedBufferPolicy',['../class_buffer_state_1_1_shared_buffer_policy.html',1,'BufferState']]],
  ['sharedcache_8982',['SharedCache',['../class_shared_cache.html',1,'']]],
  ['shd_5fwarp_5ft_8983',['shd_warp_t',['../classshd__warp__t.html',1,'']]],
  ['shiftingdynamiclimitedsharedbufferpolicy_8984',['ShiftingDynamicLimitedSharedBufferPolicy',['../class_buffer_state_1_1_shifting_dynamic_limited_shared_buffer_policy.html',1,'BufferState']]],
  ['shuffletrafficpattern_8985',['ShuffleTrafficPattern',['../class_shuffle_traffic_pattern.html',1,'']]],
  ['simd_5ffunction_5funit_8986',['simd_function_unit',['../classsimd__function__unit.html',1,'']]],
  ['simplefeedbacksharedbufferpolicy_8987',['SimpleFeedbackSharedBufferPolicy',['../class_buffer_state_1_1_simple_feedback_shared_buffer_policy.html',1,'BufferState']]],
  ['simt_5fcore_5fcluster_8988',['simt_core_cluster',['../classsimt__core__cluster.html',1,'']]],
  ['simulationinitializer_8989',['SimulationInitializer',['../class_simulation_initializer.html',1,'']]],
  ['simulator_8990',['Simulator',['../class_simulator.html',1,'']]],
  ['singlenet_8991',['SingleNet',['../class_single_net.html',1,'']]],
  ['sm_5falloc_8992',['SM_alloc',['../struct_fixed_scheduler_1_1_s_m__alloc.html',1,'FixedScheduler']]],
  ['sm_5finfo_8993',['SM_info',['../class_dynamic_scheduler_1_1_s_m__info.html',1,'DynamicScheduler']]],
  ['smartevenscheduler_8994',['SmartEvenScheduler',['../class_smart_even_scheduler.html',1,'']]],
  ['snap_5fshot_5ftrigger_8995',['snap_shot_trigger',['../classsnap__shot__trigger.html',1,'']]],
  ['solution_8996',['solution',['../structsolution.html',1,'']]],
  ['sp_5funit_8997',['sp_unit',['../classsp__unit.html',1,'']]],
  ['sparseallocator_8998',['SparseAllocator',['../class_sparse_allocator.html',1,'']]],
  ['speedentry_8999',['SpeedEntry',['../struct_wide_i_o_1_1_speed_entry.html',1,'WideIO::SpeedEntry'],['../struct_d_d_r4_1_1_speed_entry.html',1,'DDR4::SpeedEntry'],['../struct_l_p_d_d_r3_1_1_speed_entry.html',1,'LPDDR3::SpeedEntry'],['../struct_h_b_m_1_1_speed_entry.html',1,'HBM::SpeedEntry'],['../struct_wide_i_o2_1_1_speed_entry.html',1,'WideIO2::SpeedEntry'],['../struct_d_s_a_r_p_1_1_speed_entry.html',1,'DSARP::SpeedEntry'],['../struct_d_d_r3_1_1_speed_entry.html',1,'DDR3::SpeedEntry'],['../struct_l_p_d_d_r4_1_1_speed_entry.html',1,'LPDDR4::SpeedEntry'],['../struct_t_l_d_r_a_m_1_1_speed_entry.html',1,'TLDRAM::SpeedEntry'],['../struct_s_a_l_p_1_1_speed_entry.html',1,'SALP::SpeedEntry'],['../struct_a_l_d_r_a_m_1_1_speed_entry.html',1,'ALDRAM::SpeedEntry'],['../struct_g_d_d_r5_1_1_speed_entry.html',1,'GDDR5::SpeedEntry']]],
  ['speedycontroller_9000',['SpeedyController',['../class_speedy_controller.html',1,'']]],
  ['spill_5flog_5finterface_9001',['spill_log_interface',['../classspill__log__interface.html',1,'']]],
  ['srequest_9002',['sRequest',['../struct_allocator_1_1s_request.html',1,'Allocator::sRequest'],['../struct_arbiter_1_1s_request.html',1,'Arbiter::sRequest'],['../struct_priority_arbiter_1_1s_request.html',1,'PriorityArbiter::sRequest']]],
  ['ssetelement_9003',['sSetElement',['../struct_output_set_1_1s_set_element.html',1,'OutputSet']]],
  ['stack_9004',['Stack',['../struct_stack.html',1,'']]],
  ['stack_5fentry_9005',['stack_entry',['../structstack__entry.html',1,'']]],
  ['standarddeviation_9006',['StandardDeviation',['../class_stats___ram_1_1_standard_deviation.html',1,'Stats_Ram']]],
  ['standarddeviationstat_9007',['StandardDeviationStat',['../class_standard_deviation_stat.html',1,'']]],
  ['stat_9008',['Stat',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20average_20_3e_9009',['Stat&lt; Average &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20averagedeviation_20_3e_9010',['Stat&lt; AverageDeviation &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20averagevector_20_3e_9011',['Stat&lt; AverageVector &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20constvalue_20_3e_9012',['Stat&lt; ConstValue &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20distribution_20_3e_9013',['Stat&lt; Distribution &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20histogram_20_3e_9014',['Stat&lt; Histogram &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20scalar_20_3e_9015',['Stat&lt; Scalar &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20scalartype_20_3e_9016',['Stat&lt; ScalarType &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20standarddeviation_20_3e_9017',['Stat&lt; StandardDeviation &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['stat_3c_20vector_20_3e_9018',['Stat&lt; Vector &gt;',['../class_stats___ram_1_1_stat.html',1,'Stats_Ram']]],
  ['statbase_9019',['StatBase',['../class_stat_base.html',1,'StatBase&lt; StatType &gt;'],['../class_stats_1_1_stat_base.html',1,'Stats::StatBase'],['../class_stats___ram_1_1_stat_base.html',1,'Stats_Ram::StatBase']]],
  ['statbase_3c_20stats_5fram_3a_3aaverage_20_3e_9020',['StatBase&lt; Stats_Ram::Average &gt;',['../class_stat_base.html',1,'']]],
  ['statbase_3c_20stats_5fram_3a_3aaveragedeviation_20_3e_9021',['StatBase&lt; Stats_Ram::AverageDeviation &gt;',['../class_stat_base.html',1,'']]],
  ['statbase_3c_20stats_5fram_3a_3aaveragevector_20_3e_9022',['StatBase&lt; Stats_Ram::AverageVector &gt;',['../class_stat_base.html',1,'']]],
  ['statbase_3c_20stats_5fram_3a_3adistribution_20_3e_9023',['StatBase&lt; Stats_Ram::Distribution &gt;',['../class_stat_base.html',1,'']]],
  ['statbase_3c_20stats_5fram_3a_3ahistogram_20_3e_9024',['StatBase&lt; Stats_Ram::Histogram &gt;',['../class_stat_base.html',1,'']]],
  ['statbase_3c_20stats_5fram_3a_3ascalar_20_3e_9025',['StatBase&lt; Stats_Ram::Scalar &gt;',['../class_stat_base.html',1,'']]],
  ['statbase_3c_20stats_5fram_3a_3astandarddeviation_20_3e_9026',['StatBase&lt; Stats_Ram::StandardDeviation &gt;',['../class_stat_base.html',1,'']]],
  ['statbase_3c_20stats_5fram_3a_3avector_20_3e_9027',['StatBase&lt; Stats_Ram::Vector &gt;',['../class_stat_base.html',1,'']]],
  ['statbasevec_9028',['StatBaseVec',['../class_stat_base_vec.html',1,'']]],
  ['statbasevec_3c_20stats_5fram_3a_3aaveragevector_20_3e_9029',['StatBaseVec&lt; Stats_Ram::AverageVector &gt;',['../class_stat_base_vec.html',1,'']]],
  ['statbasevec_3c_20stats_5fram_3a_3avector_20_3e_9030',['StatBaseVec&lt; Stats_Ram::Vector &gt;',['../class_stat_base_vec.html',1,'']]],
  ['state_5finfo_5ft_9031',['state_info_t',['../struct_v_c_1_1state__info__t.html',1,'VC']]],
  ['staticscheduler_9032',['StaticScheduler',['../class_static_scheduler.html',1,'']]],
  ['statlist_9033',['StatList',['../class_stats___ram_1_1_stat_list.html',1,'Stats_Ram']]],
  ['stats_9034',['Stats',['../class_stats.html',1,'']]],
  ['statscomponents_9035',['statsComponents',['../classstats_components.html',1,'']]],
  ['statsdef_9036',['statsDef',['../classstats_def.html',1,'']]],
  ['stream_5fmanager_9037',['stream_manager',['../classstream__manager.html',1,'']]],
  ['stream_5foperation_9038',['stream_operation',['../classstream__operation.html',1,'']]],
  ['subarray_9039',['Subarray',['../class_subarray.html',1,'']]],
  ['switchmonitor_9040',['SwitchMonitor',['../class_switch_monitor.html',1,'']]],
  ['swl_5fscheduler_9041',['swl_scheduler',['../classswl__scheduler.html',1,'']]],
  ['symbol_9042',['symbol',['../classsymbol.html',1,'']]],
  ['symbol_5ftable_9043',['symbol_table',['../classsymbol__table.html',1,'']]],
  ['system_5fcore_9044',['system_core',['../structsystem__core.html',1,'']]],
  ['system_5fl1directory_9045',['system_L1Directory',['../structsystem___l1_directory.html',1,'']]],
  ['system_5fl2_9046',['system_L2',['../structsystem___l2.html',1,'']]],
  ['system_5fl2directory_9047',['system_L2Directory',['../structsystem___l2_directory.html',1,'']]],
  ['system_5fl3_9048',['system_L3',['../structsystem___l3.html',1,'']]],
  ['system_5fmc_9049',['system_mc',['../structsystem__mc.html',1,'']]],
  ['system_5fmem_9050',['system_mem',['../structsystem__mem.html',1,'']]],
  ['system_5fniu_9051',['system_niu',['../structsystem__niu.html',1,'']]],
  ['system_5fnoc_9052',['system_NoC',['../structsystem___no_c.html',1,'']]],
  ['system_5fpcie_9053',['system_pcie',['../structsystem__pcie.html',1,'']]]
];
